[tool.ruff]
line-length = 100
extend-exclude = [".venv", ".pytest_cache"]

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.black]
line-length = 100
target-version = ["py39"]

[tool.isort]
profile = "black"
line_length = 100

