name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install backend deps
        working-directory: backend
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          pip install ruff black isort
      - name: Lint (ruff)
        working-directory: backend
        run: |
          source .venv/bin/activate
          ruff check app
      - name: Format check (black)
        working-directory: backend
        run: |
          source .venv/bin/activate
          black --check app
      - name: Tests (pytest)
        working-directory: backend
        env:
          PYTHONPATH: ${{ github.workspace }}/backend
        run: |
          source .venv/bin/activate
          pytest -q

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "18"
      - name: Install frontend deps
        working-directory: frontend
        run: |
          npm ci --legacy-peer-deps
      - name: Lint (eslint)
        working-directory: frontend
        run: |
          npm run lint
      - name: Format check (prettier)
        working-directory: frontend
        run: |
          npx prettier --check "**/*.{ts,tsx,js,json,md,css}"










